name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfl-dev

      - name: Download Firtool Static Libraries
        run: |
          mkdir -p build
          cd build
          wget https://github.com/llvm/circt/releases/download/firtool-1.93.1/circt-full-static-linux-x64.tar.gz
          tar -xf circt-full-static-linux-x64.tar.gz

      - name: Configure CMake
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=debug -DFIRTOOL_LIB_PATH=$(pwd)/firtool-1.93.1/lib

      - name: Build
        run: |
          cd build
          make -j

      - name: Test
        run: |
          cd build
          ctest
